"use client";

import React, { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { HardwareProduct } from "@/data/hardwareDatabase";
import { KRYPTON_MAKER_PRODUCTS, KryptonMakerProduct, toHardwareProduct } from "@/data/mockProducts";
import { useCartStore } from "@/store/useCartStore";
import Hardware3DViewer from "@/components/canvas/Hardware3DViewer";

interface KryptonPDPProps {
  product: HardwareProduct;
}

export default function KryptonPDP({ product }: KryptonPDPProps) {
  const router = useRouter();
  const { addStandaloneItem } = useCartStore();
  const [activeTab, setActiveTab] = useState<"pinout" | "schematic" | "depot" | "kicad">("pinout");
  const [quantity, setQuantity] = useState(1);
  const [downloadModal, setDownloadModal] = useState<string | null>(null);
  const [toastMsg, setToastMsg] = useState<string | null>(null);

  // Check if this product corresponds to one of our rich Krypton maker products, or wrap the hardware product
  const makerItem: KryptonMakerProduct = KRYPTON_MAKER_PRODUCTS.find(
    (p) => p.slug === product.slug || p.id === product.id
  ) || {
    id: product.id,
    slug: product.slug,
    sku: product.sku,
    name: product.name,
    category: "pc-part",
    domain: "core-pc",
    brand: product.brand,
    price: product.price,
    regularPrice: product.regularPrice,
    image: product.image,
    description: product.description,
    specs: {
      formFactor: product.formFactor || "Standard Hardware",
      pins: "5-pin PCB Mount",
    },
    depotStock: {
      idbDhaka: 12,
      elephantRoad: 8,
      motijheelHq: 5,
      chattogramSanmar: 6,
    },
    kicadFootprint: `${product.brand}_${product.sku}.kicad_mod`,
    pdfDatasheet: `DS_${product.sku}_SPEC_REV1.pdf`,
    stockBinCode: "BIN-D1-04",
    status: "IN_STOCK",
  };

  const handleAddToCart = () => {
    addStandaloneItem(toHardwareProduct(makerItem), quantity);
    setToastMsg(`DISPATCHED [x${quantity}] ${makerItem.name} TO MANIFEST`);
    setTimeout(() => setToastMsg(null), 3000);
  };

  const handleBuyNow = () => {
    handleAddToCart();
    router.push("/checkout");
  };

  return (
    <main className="min-h-screen bg-[#EBEAE5] text-[#1E1E24] font-sans antialiased pb-24 selection:bg-[#FACC15] selection:text-black">
      {/* Notification Toast */}
      {toastMsg && (
        <div className="fixed top-20 right-6 z-50 bg-[#FACC15] text-black border-2 border-black px-4 py-2.5 font-mono text-xs font-bold shadow-[4px_4px_0px_#000000] animate-in fade-in slide-in-from-top-2">
          {toastMsg}
        </div>
      )}

      {/* KiCad / PDF Modal */}
      {downloadModal && (
        <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="bg-white border-4 border-black p-6 max-w-md w-full shadow-[8px_8px_0px_#000000] animate-in zoom-in-95">
            <div className="flex items-center justify-between pb-3 border-b-2 border-black mb-4">
              <span className="font-mono text-xs font-extrabold uppercase text-black">
                // FILE DOWNLOAD DISPATCH
              </span>
              <button
                onClick={() => setDownloadModal(null)}
                className="font-mono text-sm font-bold hover:text-[#EA580C]"
              >
                ✕
              </button>
            </div>

            <div className="font-mono text-xs mb-4 space-y-2">
              <div className="bg-[#EBEAE5] border border-black p-3">
                <div className="text-slate-500 text-[10px]">FILE IDENTIFIER:</div>
                <div className="font-bold text-black text-sm">{downloadModal}</div>
              </div>
              <div className="text-slate-600">
                Verified DIN-standard mechanical footprint and high-frequency impedance curves generated by Krypton CAD Lab.
              </div>
            </div>

            <div className="flex justify-end gap-2">
              <button
                onClick={() => setDownloadModal(null)}
                className="px-4 py-2 border-2 border-black font-mono text-xs font-bold uppercase hover:bg-[#EBEAE5]"
              >
                CANCEL
              </button>
              <button
                onClick={() => {
                  alert(`Downloading ${downloadModal} from Krypton Technical Repository...`);
                  setDownloadModal(null);
                }}
                className="bg-[#FACC15] hover:bg-[#FDE047] text-black border-2 border-black px-4 py-2 font-mono text-xs font-extrabold uppercase shadow-[2px_2px_0px_#000000]"
              >
                CONFIRM DOWNLOAD
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Breadcrumb Header */}
      <section className="bg-white border-b-2 border-black py-4">
        <div className="w-full max-w-[1536px] mx-auto px-4 sm:px-6 lg:px-8 flex flex-wrap items-center justify-between gap-2 font-mono text-xs">
          <div className="flex items-center gap-2 text-slate-500 uppercase">
            <Link href="/" className="hover:text-black underline">
              Krypton Depot
            </Link>
            <span>/</span>
            <Link href="/catalog" className="hover:text-black underline">
              Component Bins
            </Link>
            <span>/</span>
            <span className="text-black font-bold truncate max-w-[240px]">{makerItem.sku}</span>
          </div>

          <div className="flex items-center gap-2">
            <span className="bg-[#EBEAE5] text-black border border-black px-2 py-0.5 font-bold uppercase">
              BIN: {makerItem.stockBinCode}
            </span>
            <span className="bg-[#25D366] text-black border border-black px-2 py-0.5 font-bold uppercase">
              {makerItem.status.replace("_", " ")}
            </span>
          </div>
        </div>
      </section>

      {/* Main PDP Grid */}
      <section className="w-full max-w-[1536px] mx-auto px-4 sm:px-6 lg:px-8 pt-8">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          
          {/* Left Column: 3D Exploded / Pinout Viewer & Photos (7 cols) */}
          <div className="lg:col-span-7 space-y-6">
            
            {/* Primary Visual Bay - Pure 3D Model Always Loaded */}
            <div className="bg-white border-2 border-black p-4 sm:p-6 shadow-[6px_6px_0px_#000000]">
              <div className="flex items-center justify-between pb-3 border-b-2 border-black mb-3">
                <span className="font-mono text-xs font-bold uppercase text-black flex items-center gap-1.5">
                  <span className="w-2 h-2 rounded-full bg-[#FACC15] animate-ping" />
                  // 3D MECHANICAL HARDWARE INSPECTION BAY
                </span>
                <span className="font-mono text-[10px] text-slate-600">
                  REAL-TIME PBR WebGL 1:1
                </span>
              </div>

              <div className="w-full h-[460px] sm:h-[520px] rounded border-2 border-black overflow-hidden relative">
                <Hardware3DViewer
                  modelPath="/models/switch-cherry-mx.glb"
                  concept="krypton"
                  accentColor="#FACC15"
                  className="w-full h-full min-h-[460px]"
                />
              </div>

              <div className="mt-3 flex items-center justify-between font-mono text-xs text-slate-700">
                <span>MANUFACTURER: {makerItem.brand.toUpperCase()}</span>
                <span className="text-[#EA580C] font-bold">MIL-SPEC 3D TOLERANCE ±0.01mm</span>
              </div>
            </div>

            {/* Interactive 3D Tactile Pinout & Spec Tabs Bay */}
            <div className="bg-[#1E1E24] text-white border-2 border-black p-6 shadow-[6px_6px_0px_#000000]">
              {/* Tab Navigation */}
              <div className="flex flex-wrap items-center gap-2 border-b-2 border-white/20 pb-3 mb-4">
                {[
                  { id: "pinout", label: "01 // PINOUT & SCHEMATIC" },
                  { id: "depot", label: "02 // DEPOT INVENTORY TABLE" },
                  { id: "kicad", label: "03 // KiCad FOOTPRINTS" },
                ].map((t) => (
                  <button
                    key={t.id}
                    onClick={() => setActiveTab(t.id as typeof activeTab)}
                    className={`font-mono text-xs font-bold uppercase px-3 py-1.5 border transition-all ${
                      activeTab === t.id
                        ? "bg-[#FACC15] text-black border-[#FACC15] font-extrabold"
                        : "bg-white/10 text-slate-300 border-white/20 hover:bg-white/20"
                    }`}
                  >
                    {t.label}
                  </button>
                ))}
              </div>

              {/* Tab 1: Interactive Pinout / Schematic */}
              {activeTab === "pinout" && (
                <div className="font-mono text-xs space-y-4">
                  <div className="bg-[#121216] border border-white/20 p-4 relative overflow-hidden">
                    <div className="text-[#FACC15] font-bold text-xs mb-2">
                      // MECHANICAL PINOUT SPECIFICATION
                    </div>
                    <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 mb-3">
                      <div className="border border-white/20 p-2 bg-black/40">
                        <div className="text-[10px] text-slate-400">CONTACT PIN 1</div>
                        <div className="text-white font-bold">SIGNAL (SIG+)</div>
                      </div>
                      <div className="border border-white/20 p-2 bg-black/40">
                        <div className="text-[10px] text-slate-400">CONTACT PIN 2</div>
                        <div className="text-[#25D366] font-bold">GROUND (GND)</div>
                      </div>
                      <div className="border border-white/20 p-2 bg-black/40">
                        <div className="text-[10px] text-slate-400">CENTER STEM</div>
                        <div className="text-[#FACC15] font-bold">4.0MM POST</div>
                      </div>
                      <div className="border border-white/20 p-2 bg-black/40">
                        <div className="text-[10px] text-slate-400">SIDE PINS</div>
                        <div className="text-white font-bold">PCB STABILIZER</div>
                      </div>
                    </div>
                    <p className="text-slate-300 text-xs leading-relaxed">
                      Hot-swap compatible with standard Kailh/Gateron sockets. Reinforced beryllium copper leaf contacts rated for minimal contact bounce (&lt;5ms).
                    </p>
                  </div>
                </div>
              )}

              {/* Tab 2: Regional Physical Depot Stock Table */}
              {activeTab === "depot" && (
                <div className="font-mono text-xs">
                  <div className="border border-white/20">
                    <div className="bg-black/60 p-2.5 font-bold text-[#FACC15] border-b border-white/20 flex justify-between">
                      <span>DEPOT FACILITY</span>
                      <span>SHELF STOCK</span>
                    </div>
                    <div className="divide-y divide-white/10">
                      <div className="p-2.5 flex justify-between items-center">
                        <div>
                          <div className="font-bold text-white">IDB Bhaban Flagship, Dhaka</div>
                          <div className="text-[10px] text-slate-400">Bin Location: A2-08</div>
                        </div>
                        <span className="bg-[#25D366]/20 text-[#25D366] border border-[#25D366]/40 px-2 py-0.5 font-bold">
                          {makerItem.depotStock.idbDhaka} UNITS AVAILABLE
                        </span>
                      </div>
                      <div className="p-2.5 flex justify-between items-center">
                        <div>
                          <div className="font-bold text-white">Multiplan Center, Elephant Road</div>
                          <div className="text-[10px] text-slate-400">Bin Location: B1-14</div>
                        </div>
                        <span className="bg-[#25D366]/20 text-[#25D366] border border-[#25D366]/40 px-2 py-0.5 font-bold">
                          {makerItem.depotStock.elephantRoad} UNITS AVAILABLE
                        </span>
                      </div>
                      <div className="p-2.5 flex justify-between items-center">
                        <div>
                          <div className="font-bold text-white">Motijheel Commercial Hub</div>
                          <div className="text-[10px] text-slate-400">Bin Location: E4-02</div>
                        </div>
                        <span className="bg-[#25D366]/20 text-[#25D366] border border-[#25D366]/40 px-2 py-0.5 font-bold">
                          {makerItem.depotStock.motijheelHq} UNITS AVAILABLE
                        </span>
                      </div>
                      <div className="p-2.5 flex justify-between items-center">
                        <div>
                          <div className="font-bold text-white">Sanmar Ocean City, Chattogram</div>
                          <div className="text-[10px] text-slate-400">Bin Location: CTG-01</div>
                        </div>
                        <span className="bg-[#25D366]/20 text-[#25D366] border border-[#25D366]/40 px-2 py-0.5 font-bold">
                          {makerItem.depotStock.chattogramSanmar} UNITS AVAILABLE
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
              )}

              {/* Tab 3: KiCad Footprints & Downloads */}
              {activeTab === "kicad" && (
                <div className="font-mono text-xs space-y-3">
                  <div className="bg-[#121216] border border-white/20 p-4">
                    <div className="text-white font-bold mb-1">KiCad PCB Library Footprint:</div>
                    <div className="text-[#FACC15] text-[11px] mb-3">{makerItem.kicadFootprint}</div>
                    <button
                      onClick={() => setDownloadModal(makerItem.kicadFootprint)}
                      className="bg-[#FACC15] text-black font-extrabold px-3 py-1.5 border border-black uppercase flex items-center gap-1"
                    >
                      <span className="material-symbols-outlined text-sm">download</span>
                      <span>DOWNLOAD .KICAD_MOD</span>
                    </button>
                  </div>

                  <div className="bg-[#121216] border border-white/20 p-4">
                    <div className="text-white font-bold mb-1">Engineering PDF Datasheet:</div>
                    <div className="text-[#FACC15] text-[11px] mb-3">{makerItem.pdfDatasheet}</div>
                    <button
                      onClick={() => setDownloadModal(makerItem.pdfDatasheet)}
                      className="bg-white text-black font-extrabold px-3 py-1.5 border border-black uppercase flex items-center gap-1"
                    >
                      <span className="material-symbols-outlined text-sm">picture_as_pdf</span>
                      <span>DOWNLOAD DATASHEET</span>
                    </button>
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* Right Column: Pricing & Requisition Control Bay (5 cols) */}
          <div className="lg:col-span-5 space-y-6">
            <div className="bg-white border-2 border-black p-6 sm:p-8 shadow-[6px_6px_0px_#000000]">
              <div className="font-mono text-xs text-[#EA580C] font-bold uppercase mb-1">
                // {makerItem.domain.toUpperCase()} HARDWARE SPEC
              </div>

              <h1
                className="font-heading text-2xl sm:text-3xl font-extrabold uppercase tracking-tight text-black leading-tight mb-3"
                style={{ fontFamily: "Syne, sans-serif" }}
              >
                {makerItem.name}
              </h1>

              <div className="font-mono text-xs text-slate-500 mb-4">
                INTERNAL CODE: {makerItem.sku} • BIN: {makerItem.stockBinCode}
              </div>

              {/* Pricing Display */}
              <div className="bg-[#EBEAE5] border-2 border-black p-4 mb-6">
                <div className="flex items-baseline justify-between mb-1">
                  <span className="font-mono text-xs text-slate-500 uppercase">DEPOT PRICE:</span>
                  <span className="font-mono text-xs text-slate-400 line-through">
                    ৳ {makerItem.regularPrice.toLocaleString()}
                  </span>
                </div>
                <div className="font-mono text-3xl font-extrabold text-black">
                  ৳ {makerItem.price.toLocaleString()}
                </div>
                <div className="font-mono text-[10px] text-slate-600 mt-1">
                  * INCLUDES 7.5% REQUISITION VAT • NATIONWIDE COD DISPATCH AVAILABLE
                </div>
              </div>

              {/* Quantity Selector */}
              <div className="mb-6">
                <label className="block font-mono text-xs font-bold uppercase text-slate-700 mb-2">
                  // SELECT REQUISITION QUANTITY:
                </label>
                <div className="flex items-center gap-2">
                  <div className="flex items-center border-2 border-black bg-[#EBEAE5]">
                    <button
                      onClick={() => setQuantity(Math.max(1, quantity - 1))}
                      className="px-3 py-2 font-mono text-base font-bold hover:bg-white text-black"
                    >
                      -
                    </button>
                    <span className="w-12 text-center font-mono text-sm font-extrabold text-black">
                      {quantity}
                    </span>
                    <button
                      onClick={() => setQuantity(quantity + 1)}
                      className="px-3 py-2 font-mono text-base font-bold hover:bg-white text-black"
                    >
                      +
                    </button>
                  </div>
                  <div className="font-mono text-xs text-slate-500">
                    TOTAL: ৳ {(makerItem.price * quantity).toLocaleString()}
                  </div>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="space-y-3">
                <button
                  onClick={handleAddToCart}
                  className="w-full bg-[#FACC15] hover:bg-[#FDE047] text-black border-2 border-black py-3 px-4 font-mono text-sm font-extrabold uppercase shadow-[4px_4px_0px_#000000] active:translate-x-[3px] active:translate-y-[3px] active:shadow-none transition-all flex items-center justify-center gap-2"
                >
                  <span className="material-symbols-outlined text-base">add_shopping_cart</span>
                  <span>DISPATCH TO PARTS BIN (ADD TO CART)</span>
                </button>

                <button
                  onClick={handleBuyNow}
                  className="w-full bg-black hover:bg-[#1E1E24] text-white border-2 border-black py-3 px-4 font-mono text-sm font-bold uppercase shadow-[4px_4px_0px_#000000] active:translate-x-[3px] active:translate-y-[3px] active:shadow-none transition-all flex items-center justify-center gap-2"
                >
                  <span className="material-symbols-outlined text-base">bolt</span>
                  <span>INSTANT CHECKOUT MANIFEST</span>
                </button>

                <a
                  href={`https://wa.me/8801711000000?text=Hello%20Krypton%20Engineering%2C%20I%20have%20an%20inquiry%20regarding%20SKU%20${makerItem.sku}%20(${encodeURIComponent(makerItem.name)})`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="w-full bg-[#25D366] hover:bg-[#22c35e] text-black border-2 border-black py-2.5 px-4 font-mono text-xs font-extrabold uppercase shadow-[3px_3px_0px_#000000] active:translate-x-[2px] active:translate-y-[2px] active:shadow-none transition-all flex items-center justify-center gap-2"
                >
                  <span className="material-symbols-outlined text-base">chat</span>
                  <span>DISCUSS OVER WHATSAPP WITH ENGINEER</span>
                </a>
              </div>

              {/* Warranty & Guarantee */}
              <div className="mt-6 pt-4 border-t-2 border-black font-mono text-[11px] text-slate-600 space-y-1.5">
                <div className="flex items-center gap-2">
                  <span className="text-[#059669] font-bold">✓</span>
                  <span>2-YEAR KRYPTON LAB REPLACEMENT WARRANTY</span>
                </div>
                <div className="flex items-center gap-2">
                  <span className="text-[#059669] font-bold">✓</span>
                  <span>100% FACTORY CALIBRATED &amp; OPTICAL CONTINUITY TESTED</span>
                </div>
                <div className="flex items-center gap-2">
                  <span className="text-[#059669] font-bold">✓</span>
                  <span>PHYSICAL COUNTER INSPECTION PERMITTED BEFORE PAYMENT</span>
                </div>
              </div>
            </div>
          </div>

        </div>
      </section>
    </main>
  );
}
