import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "#b61722",
          accent: "#ef4444",
          hover: "#dc2626",
          container: "#da3437",
          fixed: "#ffdad7",
          "fixed-dim": "#ffb3ad",
        },
        "on-primary": "#ffffff",
        "on-primary-container": "#fffbff",
        "on-primary-fixed": "#410004",
        "on-primary-fixed-variant": "#930013",
        "inverse-primary": "#ffb3ad",

        secondary: {
          DEFAULT: "#565e74",
          fixed: "#dae2fd",
          "fixed-dim": "#bec6e0",
          container: "#dae2fd",
        },
        "on-secondary": "#ffffff",
        "on-secondary-container": "#5c647a",
        "on-secondary-fixed": "#131b2e",
        "on-secondary-fixed-variant": "#3f465c",

        tertiary: {
          DEFAULT: "#006947",
          container: "#00855b",
          fixed: "#6ffbbe",
          "fixed-dim": "#4edea3",
        },
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#f5fff6",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-fixed-variant": "#005236",

        error: {
          DEFAULT: "#ba1a1a",
          container: "#ffdad6",
        },
        "on-error": "#ffffff",
        "on-error-container": "#93000a",

        surface: {
          DEFAULT: "#f8f9ff",
          dim: "#ccdbf3",
          bright: "#f8f9ff",
          container: {
            lowest: "#ffffff",
            low: "#eff4ff",
            DEFAULT: "#e6eeff",
            high: "#dce9ff",
            highest: "#d5e3fc",
          },
          tint: "#b91a24",
          variant: "#d5e3fc",
        },
        "on-surface": "#0d1c2e",
        "on-surface-variant": "#5b403e",
        "inverse-surface": "#233144",
        "inverse-on-surface": "#eaf1ff",

        outline: {
          DEFAULT: "#8f6f6d",
          variant: "#e4beba",
        },

        // Dedicated Technical & Semantic Accents
        "slate-deep": "#0f172a",
        "slate-muted": "#475569",
        "slate-border": "#e2e8f0",
        "validation-green": "#10b981",
        "caution-amber": "#f59e0b",
        whatsapp: "#25d366",

        // Concept 2: NeonForge Cyberpunk Battlestation & Liquid Artisan Tokens
        neon: {
          void: "#0A0A0F",
          charcoal: "#12121A",
          surface: "#1F1F25",
          "surface-low": "#161622",
          "surface-high": "#2A292F",
          cyan: "#00F0FF",
          "cyan-dim": "rgba(0, 240, 255, 0.18)",
          orange: "#FF6B00",
          "orange-dim": "rgba(255, 107, 0, 0.2)",
          purple: "#8B5CF6",
          "purple-dim": "rgba(139, 92, 246, 0.2)",
          coolant: "#00B4D8",
          laser: "#F8FAFC",
          gunmetal: "#475569",
        },

        // Concept 3: Axiom Pro Minimalist Enterprise Workstation Tokens
        axiom: {
          canvas: "#FBFBFD",
          surface: "#FFFFFF",
          basalt: "#18181B",
          emerald: "#004F32",
          "emerald-hover": "#003823",
          "emerald-light": "#ECFDF5",
          cobalt: "#2563EB",
          titanium: "#E4E4E7",
          steel: "#52525B",
          muted: "#71717A",
          zinc: "#27272A",
        },

        // Concept 4: SynapseCAD Blueprint 3D Assembly Architect Tokens
        synapse: {
          slate: "#0F172A",
          card: "#1E293B",
          border: "#334155",
          "border-light": "#475569",
          cyan: "#06B6D4",
          "cyan-glow": "rgba(6, 182, 212, 0.4)",
          "cyan-dim": "rgba(6, 182, 212, 0.12)",
          lime: "#84CC16",
          "lime-glow": "rgba(132, 204, 22, 0.4)",
          "lime-dim": "rgba(132, 204, 22, 0.12)",
          amber: "#F59E0B",
          "amber-dim": "rgba(245, 158, 11, 0.15)",
          crimson: "#EF4444",
          "crimson-dim": "rgba(239, 68, 68, 0.15)",
          comms: "#25D366",
        },

        // Concept 5: OmniPulse BD Omnichannel Hyper-Local Retail Tokens
        omnipulse: {
          canvas: "#F4F6F9",
          surface: "#FFFFFF",
          navy: "#0D47A1",
          "navy-dark": "#0A387E",
          "navy-light": "#E3F2FD",
          amber: "#FFB300",
          "amber-hover": "#FFA000",
          "amber-light": "#FFF8E1",
          red: "#D32F2F",
          "red-light": "#FFEBEE",
          whatsapp: "#25D366",
          slate: "#1E293B",
          muted: "#64748B",
          border: "#E2E8F0",
        },
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.375rem",
        "space-md": "0.75rem",
        "space-lg": "1rem",
        "space-xl": "1.5rem",
        gutter: "0.75rem",
        "gutter-mobile": "0.5rem",
        margin: "1rem",
        "margin-mobile": "0.75rem",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.125rem",
        md: "0.25rem",
        lg: "0.375rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
        headline: ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        mono: ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        chakra: ["var(--font-chakra-petch)", "Chakra Petch", "Space Grotesk", "sans-serif"],
        jakarta: ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "Inter", "sans-serif"],
        rajdhani: ["var(--font-rajdhani)", "Rajdhani", "JetBrains Mono", "monospace"],
        "axiom-sans": ["var(--font-inter)", "Inter", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        "axiom-mono": ["var(--font-ibm-plex-mono)", "var(--font-jetbrains-mono)", "IBM Plex Mono", "monospace"],
        "synapse-mono": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "synapse-code": ["'Space Mono'", "var(--font-jetbrains-mono)", "monospace"],
        "synapse-body": ["var(--font-inter)", "Inter", "sans-serif"],
        "omnipulse-headline": ["Poppins", "var(--font-space-grotesk)", "sans-serif"],
        "omnipulse-body": ["'Open Sans'", "var(--font-inter)", "sans-serif"],
        "headline-xl": ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        "headline-lg": ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        "headline-md": ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        "headline-sm": ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "metric-display": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "metric-regular": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "spec-tag": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-xl": ["32px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-xl-mobile": ["24px", { lineHeight: "30px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["22px", { lineHeight: "28px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["15px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-sm": ["11px", { lineHeight: "16px", fontWeight: "400" }],
        "metric-display": ["20px", { lineHeight: "24px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "metric-regular": ["13px", { lineHeight: "16px", fontWeight: "500" }],
        "spec-tag": ["10.5px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-sm": ["10px", { lineHeight: "12px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
